createProduct:
  handler: src/handlers/index.createProduct
  events:
    - httpApi:
        method: POST
        path: /products

getAllProducts:
  handler: src/handlers/index.getAllProducts
  events:
    - httpApi:
        method: GET
        path: /products

deleteProduct:
  handler: src/handlers/index.deleteProduct
  events:
    - httpApi:
        method: DELETE
        path: /products/{id}

uploadProductImage:
  handler: src/handlers/index.uploadProductImage
  events:
    - httpApi:
        method: PATCH
        path: /products/image/{id}