service: product-management
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  createProduct:
    handler: src/handlers/index.createProduct
    events:
      - httpApi:
          method: POST
          path: /products

  getAllProducts:
    handler: src/handlers/index.getAllProducts
    events:
      - httpApi:
          method: GET
          path: /products

  deleteProduct:
    handler: src/handlers/index.deleteProduct
    events:
      - httpApi:
          method: DELETE
          path: /products/{id}
