service: product-management
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: src/index.handler
    events:
      - httpApi:
          method: GET
          path: /hello
